export interface CountryInfo {
  name: string;
  region: string;
  incomeGroup: string;
}

export const COUNTRY_CODES: Record<string, CountryInfo> = {
  AFG: { name: 'Afghanistan', region: 'South Asia', incomeGroup: 'Low income' },
  AGO: { name: 'Angola', region: 'Sub-Saharan Africa', incomeGroup: 'Lower middle income' },
  ARG: { name: 'Argentina', region: 'Latin America & Caribbean', incomeGroup: 'Upper middle income' },
  AUS: { name: 'Australia', region: 'East Asia & Pacific', incomeGroup: 'High income' },
  BGD: { name: 'Bangladesh', region: 'South Asia', incomeGroup: 'Lower middle income' },
  BRA: { name: 'Brazil', region: 'Latin America & Caribbean', incomeGroup: 'Upper middle income' },
  CAN: { name: 'Canada', region: 'North America', incomeGroup: 'High income' },
  CHE: { name: 'Switzerland', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  CHL: { name: 'Chile', region: 'Latin America & Caribbean', incomeGroup: 'High income' },
  CHN: { name: 'China', region: 'East Asia & Pacific', incomeGroup: 'Upper middle income' },
  CIV: { name: "Côte d'Ivoire", region: 'Sub-Saharan Africa', incomeGroup: 'Lower middle income' },
  COD: { name: 'Congo, Dem. Rep.', region: 'Sub-Saharan Africa', incomeGroup: 'Low income' },
  COL: { name: 'Colombia', region: 'Latin America & Caribbean', incomeGroup: 'Upper middle income' },
  DEU: { name: 'Germany', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  DNK: { name: 'Denmark', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  EGY: { name: 'Egypt, Arab Rep.', region: 'Middle East & North Africa', incomeGroup: 'Lower middle income' },
  ESP: { name: 'Spain', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  ETH: { name: 'Ethiopia', region: 'Sub-Saharan Africa', incomeGroup: 'Low income' },
  FIN: { name: 'Finland', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  FRA: { name: 'France', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  GBR: { name: 'United Kingdom', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  GHA: { name: 'Ghana', region: 'Sub-Saharan Africa', incomeGroup: 'Lower middle income' },
  IDN: { name: 'Indonesia', region: 'East Asia & Pacific', incomeGroup: 'Upper middle income' },
  IND: { name: 'India', region: 'South Asia', incomeGroup: 'Lower middle income' },
  IRN: { name: 'Iran, Islamic Rep.', region: 'Middle East & North Africa', incomeGroup: 'Lower middle income' },
  IRQ: { name: 'Iraq', region: 'Middle East & North Africa', incomeGroup: 'Upper middle income' },
  ITA: { name: 'Italy', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  JPN: { name: 'Japan', region: 'East Asia & Pacific', incomeGroup: 'High income' },
  KEN: { name: 'Kenya', region: 'Sub-Saharan Africa', incomeGroup: 'Lower middle income' },
  KOR: { name: 'Korea, Rep.', region: 'East Asia & Pacific', incomeGroup: 'High income' },
  LKA: { name: 'Sri Lanka', region: 'South Asia', incomeGroup: 'Lower middle income' },
  MAR: { name: 'Morocco', region: 'Middle East & North Africa', incomeGroup: 'Lower middle income' },
  MEX: { name: 'Mexico', region: 'Latin America & Caribbean', incomeGroup: 'Upper middle income' },
  MMR: { name: 'Myanmar', region: 'East Asia & Pacific', incomeGroup: 'Lower middle income' },
  MOZ: { name: 'Mozambique', region: 'Sub-Saharan Africa', incomeGroup: 'Low income' },
  MYS: { name: 'Malaysia', region: 'East Asia & Pacific', incomeGroup: 'Upper middle income' },
  NGA: { name: 'Nigeria', region: 'Sub-Saharan Africa', incomeGroup: 'Lower middle income' },
  NLD: { name: 'Netherlands', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  NOR: { name: 'Norway', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  NZL: { name: 'New Zealand', region: 'East Asia & Pacific', incomeGroup: 'High income' },
  PAK: { name: 'Pakistan', region: 'South Asia', incomeGroup: 'Lower middle income' },
  PER: { name: 'Peru', region: 'Latin America & Caribbean', incomeGroup: 'Upper middle income' },
  PHL: { name: 'Philippines', region: 'East Asia & Pacific', incomeGroup: 'Lower middle income' },
  POL: { name: 'Poland', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  PRK: { name: "Korea, Dem. People's Rep.", region: 'East Asia & Pacific', incomeGroup: 'Low income' },
  RUS: { name: 'Russian Federation', region: 'Europe & Central Asia', incomeGroup: 'Upper middle income' },
  SAU: { name: 'Saudi Arabia', region: 'Middle East & North Africa', incomeGroup: 'High income' },
  SGP: { name: 'Singapore', region: 'East Asia & Pacific', incomeGroup: 'High income' },
  SWE: { name: 'Sweden', region: 'Europe & Central Asia', incomeGroup: 'High income' },
  THA: { name: 'Thailand', region: 'East Asia & Pacific', incomeGroup: 'Upper middle income' },
  TUR: { name: 'Türkiye', region: 'Europe & Central Asia', incomeGroup: 'Upper middle income' },
  TZA: { name: 'Tanzania', region: 'Sub-Saharan Africa', incomeGroup: 'Lower middle income' },
  UGA: { name: 'Uganda', region: 'Sub-Saharan Africa', incomeGroup: 'Low income' },
  USA: { name: 'United States', region: 'North America', incomeGroup: 'High income' },
  VNM: { name: 'Viet Nam', region: 'East Asia & Pacific', incomeGroup: 'Lower middle income' },
  ZAF: { name: 'South Africa', region: 'Sub-Saharan Africa', incomeGroup: 'Upper middle income' },
  ZMB: { name: 'Zambia', region: 'Sub-Saharan Africa', incomeGroup: 'Lower middle income' },
};

export const getCountryByCode = (code: string): CountryInfo | undefined => COUNTRY_CODES[code];

export const getAllCountryCodes = (): string[] => Object.keys(COUNTRY_CODES);
